# Spring properties
spring:
  application:
    name: track-service  # Identify this application

# Map the error path to error template
error:
  path=/error

server:
  port: 8083   # HTTP (Jetty) port

# Log config
logging:
  level:
    root: INFO
  file: ./track-service.log